name: Docker action
description: A Docker based action used for testing purposes

inputs:
  who-to-greet:
    description: A person name to greet
    required: true
    default: Julian

outputs:
  answer:
    description: numeric answer to check

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}